### PR TITLE
Create it_ch.json

### PR DESCRIPTION
**Pull request by BlackShadow77**
Added italian translation for Swiss italian

### CODE REVIEW

**Comment by bl4ckscor3** [comment]
Can it_it.json be created with the same translations?

And just a note: I am no longer updating my mods for 1.17 anymore. However since I can't be bothered to deal with merging this into the 1.18 branch, I will merge it into the 1.17 one - this doesn't mean 1.17 will receive this update.

**Comment by BlackShadow77** [comment]
> Can it_it.json be created with the same translations?

it_it and it_ch are pretty similar but some words are differents so is a context problem; in shorts no, if u don't talk at least on of them

> And just a note: I am no longer updating my mods for 1.17 anymore. However since I can't be bothered to deal with merging this into the 1.18 branch, I will merge it into the 1.17 one - this doesn't mean 1.17 will receive this update.

i thought i pushed for 1.18, was a mistake, i can update translations also for 1.18 if u can't obtain that from precedent versions

**Comment by bl4ckscor3** [comment]
It's not your fault, I did not update the default branch of the repository to 1.18 prior to this pull request. I already updated the 1.18 translations, so everything is done! Thank you for the contributions :)

**Comment by BlackShadow77** [comment]
Great! Sorry for the inconvenient anyway!

**Pull request merged**
